- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks :  

  - name : version Docker
    command : docker --version
  # - name : Start Docker Service
  #   command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 imswapnil/bankapp-eta-app:latest
